name: xb_network
description: Lightweight network helper based on Dio for XB ecosystem.
version: 0.1.0
homepage: https://github.com/huisedediao/xb_scaffold.git

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.12.0'

dependencies:
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  logger: ^2.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
